### ISSUE TITLE
Bot does not return a valid image file back to the user

### ISSUE THREAD

**Issue by frandyjayr** [kenrick95/c4bot#6]
When interacting with the bot to play the game, the bot returns a broken image file back to the user, therefore the user cannot see the move that the bot plays.

![osp](https://user-images.githubusercontent.com/23549050/41133955-c42cb932-6a7e-11e8-8102-be29f0cc0e76.JPG)

**Comment by kenrick95** [comment]
Hmm, I'm not really sure if I can fix though. Let's close this issue and I'll reopen if it happens again.
